/* automatically generated by rust-bindgen 0.72.1 */

pub type Cronet_String = *const ::core::ffi::c_char;
pub type Cronet_RawDataPtr = *mut ::core::ffi::c_void;
pub type Cronet_ClientContext = *mut ::core::ffi::c_void;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Cronet_Buffer {
    _unused: [u8; 0],
}
pub type Cronet_BufferPtr = *mut Cronet_Buffer;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Cronet_BufferCallback {
    _unused: [u8; 0],
}
pub type Cronet_BufferCallbackPtr = *mut Cronet_BufferCallback;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Cronet_Runnable {
    _unused: [u8; 0],
}
pub type Cronet_RunnablePtr = *mut Cronet_Runnable;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Cronet_Executor {
    _unused: [u8; 0],
}
pub type Cronet_ExecutorPtr = *mut Cronet_Executor;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Cronet_Engine {
    _unused: [u8; 0],
}
pub type Cronet_EnginePtr = *mut Cronet_Engine;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Cronet_UrlRequestStatusListener {
    _unused: [u8; 0],
}
pub type Cronet_UrlRequestStatusListenerPtr = *mut Cronet_UrlRequestStatusListener;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Cronet_UrlRequestCallback {
    _unused: [u8; 0],
}
pub type Cronet_UrlRequestCallbackPtr = *mut Cronet_UrlRequestCallback;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Cronet_UploadDataSink {
    _unused: [u8; 0],
}
pub type Cronet_UploadDataSinkPtr = *mut Cronet_UploadDataSink;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Cronet_UploadDataProvider {
    _unused: [u8; 0],
}
pub type Cronet_UploadDataProviderPtr = *mut Cronet_UploadDataProvider;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Cronet_UrlRequest {
    _unused: [u8; 0],
}
pub type Cronet_UrlRequestPtr = *mut Cronet_UrlRequest;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Cronet_RequestFinishedInfoListener {
    _unused: [u8; 0],
}
pub type Cronet_RequestFinishedInfoListenerPtr = *mut Cronet_RequestFinishedInfoListener;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Cronet_Error {
    _unused: [u8; 0],
}
pub type Cronet_ErrorPtr = *mut Cronet_Error;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Cronet_QuicHint {
    _unused: [u8; 0],
}
pub type Cronet_QuicHintPtr = *mut Cronet_QuicHint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Cronet_PublicKeyPins {
    _unused: [u8; 0],
}
pub type Cronet_PublicKeyPinsPtr = *mut Cronet_PublicKeyPins;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Cronet_EngineParams {
    _unused: [u8; 0],
}
pub type Cronet_EngineParamsPtr = *mut Cronet_EngineParams;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Cronet_HttpHeader {
    _unused: [u8; 0],
}
pub type Cronet_HttpHeaderPtr = *mut Cronet_HttpHeader;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Cronet_UrlResponseInfo {
    _unused: [u8; 0],
}
pub type Cronet_UrlResponseInfoPtr = *mut Cronet_UrlResponseInfo;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Cronet_UrlRequestParams {
    _unused: [u8; 0],
}
pub type Cronet_UrlRequestParamsPtr = *mut Cronet_UrlRequestParams;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Cronet_DateTime {
    _unused: [u8; 0],
}
pub type Cronet_DateTimePtr = *mut Cronet_DateTime;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Cronet_Metrics {
    _unused: [u8; 0],
}
pub type Cronet_MetricsPtr = *mut Cronet_Metrics;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct Cronet_RequestFinishedInfo {
    _unused: [u8; 0],
}
pub type Cronet_RequestFinishedInfoPtr = *mut Cronet_RequestFinishedInfo;
pub const Cronet_RESULT_Cronet_RESULT_SUCCESS: Cronet_RESULT = 0;
pub const Cronet_RESULT_Cronet_RESULT_ILLEGAL_ARGUMENT: Cronet_RESULT = -100;
pub const Cronet_RESULT_Cronet_RESULT_ILLEGAL_ARGUMENT_STORAGE_PATH_MUST_EXIST: Cronet_RESULT =
    -101;
pub const Cronet_RESULT_Cronet_RESULT_ILLEGAL_ARGUMENT_INVALID_PIN: Cronet_RESULT = -102;
pub const Cronet_RESULT_Cronet_RESULT_ILLEGAL_ARGUMENT_INVALID_HOSTNAME: Cronet_RESULT = -103;
pub const Cronet_RESULT_Cronet_RESULT_ILLEGAL_ARGUMENT_INVALID_HTTP_METHOD: Cronet_RESULT = -104;
pub const Cronet_RESULT_Cronet_RESULT_ILLEGAL_ARGUMENT_INVALID_HTTP_HEADER: Cronet_RESULT = -105;
pub const Cronet_RESULT_Cronet_RESULT_ILLEGAL_STATE: Cronet_RESULT = -200;
pub const Cronet_RESULT_Cronet_RESULT_ILLEGAL_STATE_STORAGE_PATH_IN_USE: Cronet_RESULT = -201;
pub const Cronet_RESULT_Cronet_RESULT_ILLEGAL_STATE_CANNOT_SHUTDOWN_ENGINE_FROM_NETWORK_THREAD:
    Cronet_RESULT = -202;
pub const Cronet_RESULT_Cronet_RESULT_ILLEGAL_STATE_ENGINE_ALREADY_STARTED: Cronet_RESULT = -203;
pub const Cronet_RESULT_Cronet_RESULT_ILLEGAL_STATE_REQUEST_ALREADY_STARTED: Cronet_RESULT = -204;
pub const Cronet_RESULT_Cronet_RESULT_ILLEGAL_STATE_REQUEST_NOT_INITIALIZED: Cronet_RESULT = -205;
pub const Cronet_RESULT_Cronet_RESULT_ILLEGAL_STATE_REQUEST_ALREADY_INITIALIZED: Cronet_RESULT =
    -206;
pub const Cronet_RESULT_Cronet_RESULT_ILLEGAL_STATE_REQUEST_NOT_STARTED: Cronet_RESULT = -207;
pub const Cronet_RESULT_Cronet_RESULT_ILLEGAL_STATE_UNEXPECTED_REDIRECT: Cronet_RESULT = -208;
pub const Cronet_RESULT_Cronet_RESULT_ILLEGAL_STATE_UNEXPECTED_READ: Cronet_RESULT = -209;
pub const Cronet_RESULT_Cronet_RESULT_ILLEGAL_STATE_READ_FAILED: Cronet_RESULT = -210;
pub const Cronet_RESULT_Cronet_RESULT_NULL_POINTER: Cronet_RESULT = -300;
pub const Cronet_RESULT_Cronet_RESULT_NULL_POINTER_HOSTNAME: Cronet_RESULT = -301;
pub const Cronet_RESULT_Cronet_RESULT_NULL_POINTER_SHA256_PINS: Cronet_RESULT = -302;
pub const Cronet_RESULT_Cronet_RESULT_NULL_POINTER_EXPIRATION_DATE: Cronet_RESULT = -303;
pub const Cronet_RESULT_Cronet_RESULT_NULL_POINTER_ENGINE: Cronet_RESULT = -304;
pub const Cronet_RESULT_Cronet_RESULT_NULL_POINTER_URL: Cronet_RESULT = -305;
pub const Cronet_RESULT_Cronet_RESULT_NULL_POINTER_CALLBACK: Cronet_RESULT = -306;
pub const Cronet_RESULT_Cronet_RESULT_NULL_POINTER_EXECUTOR: Cronet_RESULT = -307;
pub const Cronet_RESULT_Cronet_RESULT_NULL_POINTER_METHOD: Cronet_RESULT = -308;
pub const Cronet_RESULT_Cronet_RESULT_NULL_POINTER_HEADER_NAME: Cronet_RESULT = -309;
pub const Cronet_RESULT_Cronet_RESULT_NULL_POINTER_HEADER_VALUE: Cronet_RESULT = -310;
pub const Cronet_RESULT_Cronet_RESULT_NULL_POINTER_PARAMS: Cronet_RESULT = -311;
pub const Cronet_RESULT_Cronet_RESULT_NULL_POINTER_REQUEST_FINISHED_INFO_LISTENER_EXECUTOR:
    Cronet_RESULT = -312;
pub type Cronet_RESULT = ::core::ffi::c_int;
pub const Cronet_Error_ERROR_CODE_Cronet_Error_ERROR_CODE_ERROR_CALLBACK: Cronet_Error_ERROR_CODE =
    0;
pub const Cronet_Error_ERROR_CODE_Cronet_Error_ERROR_CODE_ERROR_HOSTNAME_NOT_RESOLVED:
    Cronet_Error_ERROR_CODE = 1;
pub const Cronet_Error_ERROR_CODE_Cronet_Error_ERROR_CODE_ERROR_INTERNET_DISCONNECTED:
    Cronet_Error_ERROR_CODE = 2;
pub const Cronet_Error_ERROR_CODE_Cronet_Error_ERROR_CODE_ERROR_NETWORK_CHANGED:
    Cronet_Error_ERROR_CODE = 3;
pub const Cronet_Error_ERROR_CODE_Cronet_Error_ERROR_CODE_ERROR_TIMED_OUT: Cronet_Error_ERROR_CODE =
    4;
pub const Cronet_Error_ERROR_CODE_Cronet_Error_ERROR_CODE_ERROR_CONNECTION_CLOSED:
    Cronet_Error_ERROR_CODE = 5;
pub const Cronet_Error_ERROR_CODE_Cronet_Error_ERROR_CODE_ERROR_CONNECTION_TIMED_OUT:
    Cronet_Error_ERROR_CODE = 6;
pub const Cronet_Error_ERROR_CODE_Cronet_Error_ERROR_CODE_ERROR_CONNECTION_REFUSED:
    Cronet_Error_ERROR_CODE = 7;
pub const Cronet_Error_ERROR_CODE_Cronet_Error_ERROR_CODE_ERROR_CONNECTION_RESET:
    Cronet_Error_ERROR_CODE = 8;
pub const Cronet_Error_ERROR_CODE_Cronet_Error_ERROR_CODE_ERROR_ADDRESS_UNREACHABLE:
    Cronet_Error_ERROR_CODE = 9;
pub const Cronet_Error_ERROR_CODE_Cronet_Error_ERROR_CODE_ERROR_QUIC_PROTOCOL_FAILED:
    Cronet_Error_ERROR_CODE = 10;
pub const Cronet_Error_ERROR_CODE_Cronet_Error_ERROR_CODE_ERROR_OTHER: Cronet_Error_ERROR_CODE = 11;
pub type Cronet_Error_ERROR_CODE = ::core::ffi::c_int;
pub const Cronet_EngineParams_HTTP_CACHE_MODE_Cronet_EngineParams_HTTP_CACHE_MODE_DISABLED:
    Cronet_EngineParams_HTTP_CACHE_MODE = 0;
pub const Cronet_EngineParams_HTTP_CACHE_MODE_Cronet_EngineParams_HTTP_CACHE_MODE_IN_MEMORY:
    Cronet_EngineParams_HTTP_CACHE_MODE = 1;
pub const Cronet_EngineParams_HTTP_CACHE_MODE_Cronet_EngineParams_HTTP_CACHE_MODE_DISK_NO_HTTP:
    Cronet_EngineParams_HTTP_CACHE_MODE = 2;
pub const Cronet_EngineParams_HTTP_CACHE_MODE_Cronet_EngineParams_HTTP_CACHE_MODE_DISK:
    Cronet_EngineParams_HTTP_CACHE_MODE = 3;
pub type Cronet_EngineParams_HTTP_CACHE_MODE = ::core::ffi::c_int;
pub const Cronet_UrlRequestParams_REQUEST_PRIORITY_Cronet_UrlRequestParams_REQUEST_PRIORITY_REQUEST_PRIORITY_IDLE : Cronet_UrlRequestParams_REQUEST_PRIORITY = 0 ;
pub const Cronet_UrlRequestParams_REQUEST_PRIORITY_Cronet_UrlRequestParams_REQUEST_PRIORITY_REQUEST_PRIORITY_LOWEST : Cronet_UrlRequestParams_REQUEST_PRIORITY = 1 ;
pub const Cronet_UrlRequestParams_REQUEST_PRIORITY_Cronet_UrlRequestParams_REQUEST_PRIORITY_REQUEST_PRIORITY_LOW : Cronet_UrlRequestParams_REQUEST_PRIORITY = 2 ;
pub const Cronet_UrlRequestParams_REQUEST_PRIORITY_Cronet_UrlRequestParams_REQUEST_PRIORITY_REQUEST_PRIORITY_MEDIUM : Cronet_UrlRequestParams_REQUEST_PRIORITY = 3 ;
pub const Cronet_UrlRequestParams_REQUEST_PRIORITY_Cronet_UrlRequestParams_REQUEST_PRIORITY_REQUEST_PRIORITY_HIGHEST : Cronet_UrlRequestParams_REQUEST_PRIORITY = 4 ;
pub type Cronet_UrlRequestParams_REQUEST_PRIORITY = ::core::ffi::c_int;
pub const Cronet_UrlRequestParams_IDEMPOTENCY_Cronet_UrlRequestParams_IDEMPOTENCY_DEFAULT_IDEMPOTENCY : Cronet_UrlRequestParams_IDEMPOTENCY = 0 ;
pub const Cronet_UrlRequestParams_IDEMPOTENCY_Cronet_UrlRequestParams_IDEMPOTENCY_IDEMPOTENT:
    Cronet_UrlRequestParams_IDEMPOTENCY = 1;
pub const Cronet_UrlRequestParams_IDEMPOTENCY_Cronet_UrlRequestParams_IDEMPOTENCY_NOT_IDEMPOTENT:
    Cronet_UrlRequestParams_IDEMPOTENCY = 2;
pub type Cronet_UrlRequestParams_IDEMPOTENCY = ::core::ffi::c_int;
pub const Cronet_RequestFinishedInfo_FINISHED_REASON_Cronet_RequestFinishedInfo_FINISHED_REASON_SUCCEEDED : Cronet_RequestFinishedInfo_FINISHED_REASON = 0 ;
pub const Cronet_RequestFinishedInfo_FINISHED_REASON_Cronet_RequestFinishedInfo_FINISHED_REASON_FAILED : Cronet_RequestFinishedInfo_FINISHED_REASON = 1 ;
pub const Cronet_RequestFinishedInfo_FINISHED_REASON_Cronet_RequestFinishedInfo_FINISHED_REASON_CANCELED : Cronet_RequestFinishedInfo_FINISHED_REASON = 2 ;
pub type Cronet_RequestFinishedInfo_FINISHED_REASON = ::core::ffi::c_int;
pub const Cronet_UrlRequestStatusListener_Status_Cronet_UrlRequestStatusListener_Status_INVALID:
    Cronet_UrlRequestStatusListener_Status = -1;
pub const Cronet_UrlRequestStatusListener_Status_Cronet_UrlRequestStatusListener_Status_IDLE:
    Cronet_UrlRequestStatusListener_Status = 0;
pub const Cronet_UrlRequestStatusListener_Status_Cronet_UrlRequestStatusListener_Status_WAITING_FOR_STALLED_SOCKET_POOL : Cronet_UrlRequestStatusListener_Status = 1 ;
pub const Cronet_UrlRequestStatusListener_Status_Cronet_UrlRequestStatusListener_Status_WAITING_FOR_AVAILABLE_SOCKET : Cronet_UrlRequestStatusListener_Status = 2 ;
pub const Cronet_UrlRequestStatusListener_Status_Cronet_UrlRequestStatusListener_Status_WAITING_FOR_DELEGATE : Cronet_UrlRequestStatusListener_Status = 3 ;
pub const Cronet_UrlRequestStatusListener_Status_Cronet_UrlRequestStatusListener_Status_WAITING_FOR_CACHE : Cronet_UrlRequestStatusListener_Status = 4 ;
pub const Cronet_UrlRequestStatusListener_Status_Cronet_UrlRequestStatusListener_Status_DOWNLOADING_PAC_FILE : Cronet_UrlRequestStatusListener_Status = 5 ;
pub const Cronet_UrlRequestStatusListener_Status_Cronet_UrlRequestStatusListener_Status_RESOLVING_PROXY_FOR_URL : Cronet_UrlRequestStatusListener_Status = 6 ;
pub const Cronet_UrlRequestStatusListener_Status_Cronet_UrlRequestStatusListener_Status_RESOLVING_HOST_IN_PAC_FILE : Cronet_UrlRequestStatusListener_Status = 7 ;
pub const Cronet_UrlRequestStatusListener_Status_Cronet_UrlRequestStatusListener_Status_ESTABLISHING_PROXY_TUNNEL : Cronet_UrlRequestStatusListener_Status = 8 ;
pub const Cronet_UrlRequestStatusListener_Status_Cronet_UrlRequestStatusListener_Status_RESOLVING_HOST : Cronet_UrlRequestStatusListener_Status = 9 ;
pub const Cronet_UrlRequestStatusListener_Status_Cronet_UrlRequestStatusListener_Status_CONNECTING : Cronet_UrlRequestStatusListener_Status = 10 ;
pub const Cronet_UrlRequestStatusListener_Status_Cronet_UrlRequestStatusListener_Status_SSL_HANDSHAKE : Cronet_UrlRequestStatusListener_Status = 11 ;
pub const Cronet_UrlRequestStatusListener_Status_Cronet_UrlRequestStatusListener_Status_SENDING_REQUEST : Cronet_UrlRequestStatusListener_Status = 12 ;
pub const Cronet_UrlRequestStatusListener_Status_Cronet_UrlRequestStatusListener_Status_WAITING_FOR_RESPONSE : Cronet_UrlRequestStatusListener_Status = 13 ;
pub const Cronet_UrlRequestStatusListener_Status_Cronet_UrlRequestStatusListener_Status_READING_RESPONSE : Cronet_UrlRequestStatusListener_Status = 14 ;
pub type Cronet_UrlRequestStatusListener_Status = ::core::ffi::c_int;
unsafe extern "C" {
    pub fn Cronet_Buffer_Create() -> Cronet_BufferPtr;
}
unsafe extern "C" {
    pub fn Cronet_Buffer_Destroy(self_: Cronet_BufferPtr);
}
unsafe extern "C" {
    pub fn Cronet_Buffer_SetClientContext(
        self_: Cronet_BufferPtr,
        client_context: Cronet_ClientContext,
    );
}
unsafe extern "C" {
    pub fn Cronet_Buffer_GetClientContext(self_: Cronet_BufferPtr) -> Cronet_ClientContext;
}
unsafe extern "C" {
    pub fn Cronet_Buffer_InitWithDataAndCallback(
        self_: Cronet_BufferPtr,
        data: Cronet_RawDataPtr,
        size: u64,
        callback: Cronet_BufferCallbackPtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_Buffer_InitWithAlloc(self_: Cronet_BufferPtr, size: u64);
}
unsafe extern "C" {
    pub fn Cronet_Buffer_GetSize(self_: Cronet_BufferPtr) -> u64;
}
unsafe extern "C" {
    pub fn Cronet_Buffer_GetData(self_: Cronet_BufferPtr) -> Cronet_RawDataPtr;
}
pub type Cronet_Buffer_InitWithDataAndCallbackFunc = ::core::option::Option<
    unsafe extern "C" fn(
        self_: Cronet_BufferPtr,
        data: Cronet_RawDataPtr,
        size: u64,
        callback: Cronet_BufferCallbackPtr,
    ),
>;
pub type Cronet_Buffer_InitWithAllocFunc =
    ::core::option::Option<unsafe extern "C" fn(self_: Cronet_BufferPtr, size: u64)>;
pub type Cronet_Buffer_GetSizeFunc =
    ::core::option::Option<unsafe extern "C" fn(self_: Cronet_BufferPtr) -> u64>;
pub type Cronet_Buffer_GetDataFunc =
    ::core::option::Option<unsafe extern "C" fn(self_: Cronet_BufferPtr) -> Cronet_RawDataPtr>;
unsafe extern "C" {
    pub fn Cronet_Buffer_CreateWith(
        InitWithDataAndCallbackFunc: Cronet_Buffer_InitWithDataAndCallbackFunc,
        InitWithAllocFunc: Cronet_Buffer_InitWithAllocFunc,
        GetSizeFunc: Cronet_Buffer_GetSizeFunc,
        GetDataFunc: Cronet_Buffer_GetDataFunc,
    ) -> Cronet_BufferPtr;
}
unsafe extern "C" {
    pub fn Cronet_BufferCallback_Destroy(self_: Cronet_BufferCallbackPtr);
}
unsafe extern "C" {
    pub fn Cronet_BufferCallback_SetClientContext(
        self_: Cronet_BufferCallbackPtr,
        client_context: Cronet_ClientContext,
    );
}
unsafe extern "C" {
    pub fn Cronet_BufferCallback_GetClientContext(
        self_: Cronet_BufferCallbackPtr,
    ) -> Cronet_ClientContext;
}
unsafe extern "C" {
    pub fn Cronet_BufferCallback_OnDestroy(
        self_: Cronet_BufferCallbackPtr,
        buffer: Cronet_BufferPtr,
    );
}
pub type Cronet_BufferCallback_OnDestroyFunc = ::core::option::Option<
    unsafe extern "C" fn(self_: Cronet_BufferCallbackPtr, buffer: Cronet_BufferPtr),
>;
unsafe extern "C" {
    pub fn Cronet_BufferCallback_CreateWith(
        OnDestroyFunc: Cronet_BufferCallback_OnDestroyFunc,
    ) -> Cronet_BufferCallbackPtr;
}
unsafe extern "C" {
    pub fn Cronet_Runnable_Destroy(self_: Cronet_RunnablePtr);
}
unsafe extern "C" {
    pub fn Cronet_Runnable_SetClientContext(
        self_: Cronet_RunnablePtr,
        client_context: Cronet_ClientContext,
    );
}
unsafe extern "C" {
    pub fn Cronet_Runnable_GetClientContext(self_: Cronet_RunnablePtr) -> Cronet_ClientContext;
}
unsafe extern "C" {
    pub fn Cronet_Runnable_Run(self_: Cronet_RunnablePtr);
}
pub type Cronet_Runnable_RunFunc =
    ::core::option::Option<unsafe extern "C" fn(self_: Cronet_RunnablePtr)>;
unsafe extern "C" {
    pub fn Cronet_Runnable_CreateWith(RunFunc: Cronet_Runnable_RunFunc) -> Cronet_RunnablePtr;
}
unsafe extern "C" {
    pub fn Cronet_Executor_Destroy(self_: Cronet_ExecutorPtr);
}
unsafe extern "C" {
    pub fn Cronet_Executor_SetClientContext(
        self_: Cronet_ExecutorPtr,
        client_context: Cronet_ClientContext,
    );
}
unsafe extern "C" {
    pub fn Cronet_Executor_GetClientContext(self_: Cronet_ExecutorPtr) -> Cronet_ClientContext;
}
unsafe extern "C" {
    pub fn Cronet_Executor_Execute(self_: Cronet_ExecutorPtr, command: Cronet_RunnablePtr);
}
pub type Cronet_Executor_ExecuteFunc = ::core::option::Option<
    unsafe extern "C" fn(self_: Cronet_ExecutorPtr, command: Cronet_RunnablePtr),
>;
unsafe extern "C" {
    pub fn Cronet_Executor_CreateWith(
        ExecuteFunc: Cronet_Executor_ExecuteFunc,
    ) -> Cronet_ExecutorPtr;
}
unsafe extern "C" {
    pub fn Cronet_Engine_Create() -> Cronet_EnginePtr;
}
unsafe extern "C" {
    pub fn Cronet_Engine_Destroy(self_: Cronet_EnginePtr);
}
unsafe extern "C" {
    pub fn Cronet_Engine_SetClientContext(
        self_: Cronet_EnginePtr,
        client_context: Cronet_ClientContext,
    );
}
unsafe extern "C" {
    pub fn Cronet_Engine_GetClientContext(self_: Cronet_EnginePtr) -> Cronet_ClientContext;
}
unsafe extern "C" {
    pub fn Cronet_Engine_StartWithParams(
        self_: Cronet_EnginePtr,
        params: Cronet_EngineParamsPtr,
    ) -> Cronet_RESULT;
}
unsafe extern "C" {
    pub fn Cronet_Engine_StartNetLogToFile(
        self_: Cronet_EnginePtr,
        file_name: Cronet_String,
        log_all: bool,
    ) -> bool;
}
unsafe extern "C" {
    pub fn Cronet_Engine_StopNetLog(self_: Cronet_EnginePtr);
}
unsafe extern "C" {
    pub fn Cronet_Engine_Shutdown(self_: Cronet_EnginePtr) -> Cronet_RESULT;
}
unsafe extern "C" {
    pub fn Cronet_Engine_GetVersionString(self_: Cronet_EnginePtr) -> Cronet_String;
}
unsafe extern "C" {
    pub fn Cronet_Engine_GetDefaultUserAgent(self_: Cronet_EnginePtr) -> Cronet_String;
}
unsafe extern "C" {
    pub fn Cronet_Engine_AddRequestFinishedListener(
        self_: Cronet_EnginePtr,
        listener: Cronet_RequestFinishedInfoListenerPtr,
        executor: Cronet_ExecutorPtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_Engine_RemoveRequestFinishedListener(
        self_: Cronet_EnginePtr,
        listener: Cronet_RequestFinishedInfoListenerPtr,
    );
}
pub type Cronet_Engine_StartWithParamsFunc = ::core::option::Option<
    unsafe extern "C" fn(self_: Cronet_EnginePtr, params: Cronet_EngineParamsPtr) -> Cronet_RESULT,
>;
pub type Cronet_Engine_StartNetLogToFileFunc = ::core::option::Option<
    unsafe extern "C" fn(self_: Cronet_EnginePtr, file_name: Cronet_String, log_all: bool) -> bool,
>;
pub type Cronet_Engine_StopNetLogFunc =
    ::core::option::Option<unsafe extern "C" fn(self_: Cronet_EnginePtr)>;
pub type Cronet_Engine_ShutdownFunc =
    ::core::option::Option<unsafe extern "C" fn(self_: Cronet_EnginePtr) -> Cronet_RESULT>;
pub type Cronet_Engine_GetVersionStringFunc =
    ::core::option::Option<unsafe extern "C" fn(self_: Cronet_EnginePtr) -> Cronet_String>;
pub type Cronet_Engine_GetDefaultUserAgentFunc =
    ::core::option::Option<unsafe extern "C" fn(self_: Cronet_EnginePtr) -> Cronet_String>;
pub type Cronet_Engine_AddRequestFinishedListenerFunc = ::core::option::Option<
    unsafe extern "C" fn(
        self_: Cronet_EnginePtr,
        listener: Cronet_RequestFinishedInfoListenerPtr,
        executor: Cronet_ExecutorPtr,
    ),
>;
pub type Cronet_Engine_RemoveRequestFinishedListenerFunc = ::core::option::Option<
    unsafe extern "C" fn(self_: Cronet_EnginePtr, listener: Cronet_RequestFinishedInfoListenerPtr),
>;
unsafe extern "C" {
    pub fn Cronet_Engine_CreateWith(
        StartWithParamsFunc: Cronet_Engine_StartWithParamsFunc,
        StartNetLogToFileFunc: Cronet_Engine_StartNetLogToFileFunc,
        StopNetLogFunc: Cronet_Engine_StopNetLogFunc,
        ShutdownFunc: Cronet_Engine_ShutdownFunc,
        GetVersionStringFunc: Cronet_Engine_GetVersionStringFunc,
        GetDefaultUserAgentFunc: Cronet_Engine_GetDefaultUserAgentFunc,
        AddRequestFinishedListenerFunc: Cronet_Engine_AddRequestFinishedListenerFunc,
        RemoveRequestFinishedListenerFunc: Cronet_Engine_RemoveRequestFinishedListenerFunc,
    ) -> Cronet_EnginePtr;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestStatusListener_Destroy(self_: Cronet_UrlRequestStatusListenerPtr);
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestStatusListener_SetClientContext(
        self_: Cronet_UrlRequestStatusListenerPtr,
        client_context: Cronet_ClientContext,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestStatusListener_GetClientContext(
        self_: Cronet_UrlRequestStatusListenerPtr,
    ) -> Cronet_ClientContext;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestStatusListener_OnStatus(
        self_: Cronet_UrlRequestStatusListenerPtr,
        status: Cronet_UrlRequestStatusListener_Status,
    );
}
pub type Cronet_UrlRequestStatusListener_OnStatusFunc = ::core::option::Option<
    unsafe extern "C" fn(
        self_: Cronet_UrlRequestStatusListenerPtr,
        status: Cronet_UrlRequestStatusListener_Status,
    ),
>;
unsafe extern "C" {
    pub fn Cronet_UrlRequestStatusListener_CreateWith(
        OnStatusFunc: Cronet_UrlRequestStatusListener_OnStatusFunc,
    ) -> Cronet_UrlRequestStatusListenerPtr;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestCallback_Destroy(self_: Cronet_UrlRequestCallbackPtr);
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestCallback_SetClientContext(
        self_: Cronet_UrlRequestCallbackPtr,
        client_context: Cronet_ClientContext,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestCallback_GetClientContext(
        self_: Cronet_UrlRequestCallbackPtr,
    ) -> Cronet_ClientContext;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestCallback_OnRedirectReceived(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
        new_location_url: Cronet_String,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestCallback_OnResponseStarted(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestCallback_OnReadCompleted(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
        buffer: Cronet_BufferPtr,
        bytes_read: u64,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestCallback_OnSucceeded(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestCallback_OnFailed(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
        error: Cronet_ErrorPtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestCallback_OnCanceled(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
    );
}
pub type Cronet_UrlRequestCallback_OnRedirectReceivedFunc = ::core::option::Option<
    unsafe extern "C" fn(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
        new_location_url: Cronet_String,
    ),
>;
pub type Cronet_UrlRequestCallback_OnResponseStartedFunc = ::core::option::Option<
    unsafe extern "C" fn(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
    ),
>;
pub type Cronet_UrlRequestCallback_OnReadCompletedFunc = ::core::option::Option<
    unsafe extern "C" fn(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
        buffer: Cronet_BufferPtr,
        bytes_read: u64,
    ),
>;
pub type Cronet_UrlRequestCallback_OnSucceededFunc = ::core::option::Option<
    unsafe extern "C" fn(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
    ),
>;
pub type Cronet_UrlRequestCallback_OnFailedFunc = ::core::option::Option<
    unsafe extern "C" fn(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
        error: Cronet_ErrorPtr,
    ),
>;
pub type Cronet_UrlRequestCallback_OnCanceledFunc = ::core::option::Option<
    unsafe extern "C" fn(
        self_: Cronet_UrlRequestCallbackPtr,
        request: Cronet_UrlRequestPtr,
        info: Cronet_UrlResponseInfoPtr,
    ),
>;
unsafe extern "C" {
    pub fn Cronet_UrlRequestCallback_CreateWith(
        OnRedirectReceivedFunc: Cronet_UrlRequestCallback_OnRedirectReceivedFunc,
        OnResponseStartedFunc: Cronet_UrlRequestCallback_OnResponseStartedFunc,
        OnReadCompletedFunc: Cronet_UrlRequestCallback_OnReadCompletedFunc,
        OnSucceededFunc: Cronet_UrlRequestCallback_OnSucceededFunc,
        OnFailedFunc: Cronet_UrlRequestCallback_OnFailedFunc,
        OnCanceledFunc: Cronet_UrlRequestCallback_OnCanceledFunc,
    ) -> Cronet_UrlRequestCallbackPtr;
}
unsafe extern "C" {
    pub fn Cronet_UploadDataSink_Create() -> Cronet_UploadDataSinkPtr;
}
unsafe extern "C" {
    pub fn Cronet_UploadDataSink_Destroy(self_: Cronet_UploadDataSinkPtr);
}
unsafe extern "C" {
    pub fn Cronet_UploadDataSink_SetClientContext(
        self_: Cronet_UploadDataSinkPtr,
        client_context: Cronet_ClientContext,
    );
}
unsafe extern "C" {
    pub fn Cronet_UploadDataSink_GetClientContext(
        self_: Cronet_UploadDataSinkPtr,
    ) -> Cronet_ClientContext;
}
unsafe extern "C" {
    pub fn Cronet_UploadDataSink_OnReadSucceeded(
        self_: Cronet_UploadDataSinkPtr,
        bytes_read: u64,
        final_chunk: bool,
    );
}
unsafe extern "C" {
    pub fn Cronet_UploadDataSink_OnReadError(
        self_: Cronet_UploadDataSinkPtr,
        error_message: Cronet_String,
    );
}
unsafe extern "C" {
    pub fn Cronet_UploadDataSink_OnRewindSucceeded(self_: Cronet_UploadDataSinkPtr);
}
unsafe extern "C" {
    pub fn Cronet_UploadDataSink_OnRewindError(
        self_: Cronet_UploadDataSinkPtr,
        error_message: Cronet_String,
    );
}
pub type Cronet_UploadDataSink_OnReadSucceededFunc = ::core::option::Option<
    unsafe extern "C" fn(self_: Cronet_UploadDataSinkPtr, bytes_read: u64, final_chunk: bool),
>;
pub type Cronet_UploadDataSink_OnReadErrorFunc = ::core::option::Option<
    unsafe extern "C" fn(self_: Cronet_UploadDataSinkPtr, error_message: Cronet_String),
>;
pub type Cronet_UploadDataSink_OnRewindSucceededFunc =
    ::core::option::Option<unsafe extern "C" fn(self_: Cronet_UploadDataSinkPtr)>;
pub type Cronet_UploadDataSink_OnRewindErrorFunc = ::core::option::Option<
    unsafe extern "C" fn(self_: Cronet_UploadDataSinkPtr, error_message: Cronet_String),
>;
unsafe extern "C" {
    pub fn Cronet_UploadDataSink_CreateWith(
        OnReadSucceededFunc: Cronet_UploadDataSink_OnReadSucceededFunc,
        OnReadErrorFunc: Cronet_UploadDataSink_OnReadErrorFunc,
        OnRewindSucceededFunc: Cronet_UploadDataSink_OnRewindSucceededFunc,
        OnRewindErrorFunc: Cronet_UploadDataSink_OnRewindErrorFunc,
    ) -> Cronet_UploadDataSinkPtr;
}
unsafe extern "C" {
    pub fn Cronet_UploadDataProvider_Destroy(self_: Cronet_UploadDataProviderPtr);
}
unsafe extern "C" {
    pub fn Cronet_UploadDataProvider_SetClientContext(
        self_: Cronet_UploadDataProviderPtr,
        client_context: Cronet_ClientContext,
    );
}
unsafe extern "C" {
    pub fn Cronet_UploadDataProvider_GetClientContext(
        self_: Cronet_UploadDataProviderPtr,
    ) -> Cronet_ClientContext;
}
unsafe extern "C" {
    pub fn Cronet_UploadDataProvider_GetLength(self_: Cronet_UploadDataProviderPtr) -> i64;
}
unsafe extern "C" {
    pub fn Cronet_UploadDataProvider_Read(
        self_: Cronet_UploadDataProviderPtr,
        upload_data_sink: Cronet_UploadDataSinkPtr,
        buffer: Cronet_BufferPtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_UploadDataProvider_Rewind(
        self_: Cronet_UploadDataProviderPtr,
        upload_data_sink: Cronet_UploadDataSinkPtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_UploadDataProvider_Close(self_: Cronet_UploadDataProviderPtr);
}
pub type Cronet_UploadDataProvider_GetLengthFunc =
    ::core::option::Option<unsafe extern "C" fn(self_: Cronet_UploadDataProviderPtr) -> i64>;
pub type Cronet_UploadDataProvider_ReadFunc = ::core::option::Option<
    unsafe extern "C" fn(
        self_: Cronet_UploadDataProviderPtr,
        upload_data_sink: Cronet_UploadDataSinkPtr,
        buffer: Cronet_BufferPtr,
    ),
>;
pub type Cronet_UploadDataProvider_RewindFunc = ::core::option::Option<
    unsafe extern "C" fn(
        self_: Cronet_UploadDataProviderPtr,
        upload_data_sink: Cronet_UploadDataSinkPtr,
    ),
>;
pub type Cronet_UploadDataProvider_CloseFunc =
    ::core::option::Option<unsafe extern "C" fn(self_: Cronet_UploadDataProviderPtr)>;
unsafe extern "C" {
    pub fn Cronet_UploadDataProvider_CreateWith(
        GetLengthFunc: Cronet_UploadDataProvider_GetLengthFunc,
        ReadFunc: Cronet_UploadDataProvider_ReadFunc,
        RewindFunc: Cronet_UploadDataProvider_RewindFunc,
        CloseFunc: Cronet_UploadDataProvider_CloseFunc,
    ) -> Cronet_UploadDataProviderPtr;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequest_Create() -> Cronet_UrlRequestPtr;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequest_Destroy(self_: Cronet_UrlRequestPtr);
}
unsafe extern "C" {
    pub fn Cronet_UrlRequest_SetClientContext(
        self_: Cronet_UrlRequestPtr,
        client_context: Cronet_ClientContext,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlRequest_GetClientContext(self_: Cronet_UrlRequestPtr) -> Cronet_ClientContext;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequest_InitWithParams(
        self_: Cronet_UrlRequestPtr,
        engine: Cronet_EnginePtr,
        url: Cronet_String,
        params: Cronet_UrlRequestParamsPtr,
        callback: Cronet_UrlRequestCallbackPtr,
        executor: Cronet_ExecutorPtr,
    ) -> Cronet_RESULT;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequest_Start(self_: Cronet_UrlRequestPtr) -> Cronet_RESULT;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequest_FollowRedirect(self_: Cronet_UrlRequestPtr) -> Cronet_RESULT;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequest_Read(
        self_: Cronet_UrlRequestPtr,
        buffer: Cronet_BufferPtr,
    ) -> Cronet_RESULT;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequest_Cancel(self_: Cronet_UrlRequestPtr);
}
unsafe extern "C" {
    pub fn Cronet_UrlRequest_IsDone(self_: Cronet_UrlRequestPtr) -> bool;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequest_GetStatus(
        self_: Cronet_UrlRequestPtr,
        listener: Cronet_UrlRequestStatusListenerPtr,
    );
}
pub type Cronet_UrlRequest_InitWithParamsFunc = ::core::option::Option<
    unsafe extern "C" fn(
        self_: Cronet_UrlRequestPtr,
        engine: Cronet_EnginePtr,
        url: Cronet_String,
        params: Cronet_UrlRequestParamsPtr,
        callback: Cronet_UrlRequestCallbackPtr,
        executor: Cronet_ExecutorPtr,
    ) -> Cronet_RESULT,
>;
pub type Cronet_UrlRequest_StartFunc =
    ::core::option::Option<unsafe extern "C" fn(self_: Cronet_UrlRequestPtr) -> Cronet_RESULT>;
pub type Cronet_UrlRequest_FollowRedirectFunc =
    ::core::option::Option<unsafe extern "C" fn(self_: Cronet_UrlRequestPtr) -> Cronet_RESULT>;
pub type Cronet_UrlRequest_ReadFunc = ::core::option::Option<
    unsafe extern "C" fn(self_: Cronet_UrlRequestPtr, buffer: Cronet_BufferPtr) -> Cronet_RESULT,
>;
pub type Cronet_UrlRequest_CancelFunc =
    ::core::option::Option<unsafe extern "C" fn(self_: Cronet_UrlRequestPtr)>;
pub type Cronet_UrlRequest_IsDoneFunc =
    ::core::option::Option<unsafe extern "C" fn(self_: Cronet_UrlRequestPtr) -> bool>;
pub type Cronet_UrlRequest_GetStatusFunc = ::core::option::Option<
    unsafe extern "C" fn(self_: Cronet_UrlRequestPtr, listener: Cronet_UrlRequestStatusListenerPtr),
>;
unsafe extern "C" {
    pub fn Cronet_UrlRequest_CreateWith(
        InitWithParamsFunc: Cronet_UrlRequest_InitWithParamsFunc,
        StartFunc: Cronet_UrlRequest_StartFunc,
        FollowRedirectFunc: Cronet_UrlRequest_FollowRedirectFunc,
        ReadFunc: Cronet_UrlRequest_ReadFunc,
        CancelFunc: Cronet_UrlRequest_CancelFunc,
        IsDoneFunc: Cronet_UrlRequest_IsDoneFunc,
        GetStatusFunc: Cronet_UrlRequest_GetStatusFunc,
    ) -> Cronet_UrlRequestPtr;
}
unsafe extern "C" {
    pub fn Cronet_RequestFinishedInfoListener_Destroy(self_: Cronet_RequestFinishedInfoListenerPtr);
}
unsafe extern "C" {
    pub fn Cronet_RequestFinishedInfoListener_SetClientContext(
        self_: Cronet_RequestFinishedInfoListenerPtr,
        client_context: Cronet_ClientContext,
    );
}
unsafe extern "C" {
    pub fn Cronet_RequestFinishedInfoListener_GetClientContext(
        self_: Cronet_RequestFinishedInfoListenerPtr,
    ) -> Cronet_ClientContext;
}
unsafe extern "C" {
    pub fn Cronet_RequestFinishedInfoListener_OnRequestFinished(
        self_: Cronet_RequestFinishedInfoListenerPtr,
        request_info: Cronet_RequestFinishedInfoPtr,
        response_info: Cronet_UrlResponseInfoPtr,
        error: Cronet_ErrorPtr,
    );
}
pub type Cronet_RequestFinishedInfoListener_OnRequestFinishedFunc = ::core::option::Option<
    unsafe extern "C" fn(
        self_: Cronet_RequestFinishedInfoListenerPtr,
        request_info: Cronet_RequestFinishedInfoPtr,
        response_info: Cronet_UrlResponseInfoPtr,
        error: Cronet_ErrorPtr,
    ),
>;
unsafe extern "C" {
    pub fn Cronet_RequestFinishedInfoListener_CreateWith(
        OnRequestFinishedFunc: Cronet_RequestFinishedInfoListener_OnRequestFinishedFunc,
    ) -> Cronet_RequestFinishedInfoListenerPtr;
}
unsafe extern "C" {
    pub fn Cronet_Error_Create() -> Cronet_ErrorPtr;
}
unsafe extern "C" {
    pub fn Cronet_Error_Destroy(self_: Cronet_ErrorPtr);
}
unsafe extern "C" {
    pub fn Cronet_Error_error_code_set(self_: Cronet_ErrorPtr, error_code: Cronet_Error_ERROR_CODE);
}
unsafe extern "C" {
    pub fn Cronet_Error_message_set(self_: Cronet_ErrorPtr, message: Cronet_String);
}
unsafe extern "C" {
    pub fn Cronet_Error_internal_error_code_set(self_: Cronet_ErrorPtr, internal_error_code: i32);
}
unsafe extern "C" {
    pub fn Cronet_Error_immediately_retryable_set(
        self_: Cronet_ErrorPtr,
        immediately_retryable: bool,
    );
}
unsafe extern "C" {
    pub fn Cronet_Error_quic_detailed_error_code_set(
        self_: Cronet_ErrorPtr,
        quic_detailed_error_code: i32,
    );
}
unsafe extern "C" {
    pub fn Cronet_Error_error_code_get(self_: Cronet_ErrorPtr) -> Cronet_Error_ERROR_CODE;
}
unsafe extern "C" {
    pub fn Cronet_Error_message_get(self_: Cronet_ErrorPtr) -> Cronet_String;
}
unsafe extern "C" {
    pub fn Cronet_Error_internal_error_code_get(self_: Cronet_ErrorPtr) -> i32;
}
unsafe extern "C" {
    pub fn Cronet_Error_immediately_retryable_get(self_: Cronet_ErrorPtr) -> bool;
}
unsafe extern "C" {
    pub fn Cronet_Error_quic_detailed_error_code_get(self_: Cronet_ErrorPtr) -> i32;
}
unsafe extern "C" {
    pub fn Cronet_QuicHint_Create() -> Cronet_QuicHintPtr;
}
unsafe extern "C" {
    pub fn Cronet_QuicHint_Destroy(self_: Cronet_QuicHintPtr);
}
unsafe extern "C" {
    pub fn Cronet_QuicHint_host_set(self_: Cronet_QuicHintPtr, host: Cronet_String);
}
unsafe extern "C" {
    pub fn Cronet_QuicHint_port_set(self_: Cronet_QuicHintPtr, port: i32);
}
unsafe extern "C" {
    pub fn Cronet_QuicHint_alternate_port_set(self_: Cronet_QuicHintPtr, alternate_port: i32);
}
unsafe extern "C" {
    pub fn Cronet_QuicHint_host_get(self_: Cronet_QuicHintPtr) -> Cronet_String;
}
unsafe extern "C" {
    pub fn Cronet_QuicHint_port_get(self_: Cronet_QuicHintPtr) -> i32;
}
unsafe extern "C" {
    pub fn Cronet_QuicHint_alternate_port_get(self_: Cronet_QuicHintPtr) -> i32;
}
unsafe extern "C" {
    pub fn Cronet_PublicKeyPins_Create() -> Cronet_PublicKeyPinsPtr;
}
unsafe extern "C" {
    pub fn Cronet_PublicKeyPins_Destroy(self_: Cronet_PublicKeyPinsPtr);
}
unsafe extern "C" {
    pub fn Cronet_PublicKeyPins_host_set(self_: Cronet_PublicKeyPinsPtr, host: Cronet_String);
}
unsafe extern "C" {
    pub fn Cronet_PublicKeyPins_pins_sha256_add(
        self_: Cronet_PublicKeyPinsPtr,
        element: Cronet_String,
    );
}
unsafe extern "C" {
    pub fn Cronet_PublicKeyPins_include_subdomains_set(
        self_: Cronet_PublicKeyPinsPtr,
        include_subdomains: bool,
    );
}
unsafe extern "C" {
    pub fn Cronet_PublicKeyPins_expiration_date_set(
        self_: Cronet_PublicKeyPinsPtr,
        expiration_date: i64,
    );
}
unsafe extern "C" {
    pub fn Cronet_PublicKeyPins_host_get(self_: Cronet_PublicKeyPinsPtr) -> Cronet_String;
}
unsafe extern "C" {
    pub fn Cronet_PublicKeyPins_pins_sha256_size(self_: Cronet_PublicKeyPinsPtr) -> u32;
}
unsafe extern "C" {
    pub fn Cronet_PublicKeyPins_pins_sha256_at(
        self_: Cronet_PublicKeyPinsPtr,
        index: u32,
    ) -> Cronet_String;
}
unsafe extern "C" {
    pub fn Cronet_PublicKeyPins_pins_sha256_clear(self_: Cronet_PublicKeyPinsPtr);
}
unsafe extern "C" {
    pub fn Cronet_PublicKeyPins_include_subdomains_get(self_: Cronet_PublicKeyPinsPtr) -> bool;
}
unsafe extern "C" {
    pub fn Cronet_PublicKeyPins_expiration_date_get(self_: Cronet_PublicKeyPinsPtr) -> i64;
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_Create() -> Cronet_EngineParamsPtr;
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_Destroy(self_: Cronet_EngineParamsPtr);
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_enable_check_result_set(
        self_: Cronet_EngineParamsPtr,
        enable_check_result: bool,
    );
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_user_agent_set(
        self_: Cronet_EngineParamsPtr,
        user_agent: Cronet_String,
    );
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_accept_language_set(
        self_: Cronet_EngineParamsPtr,
        accept_language: Cronet_String,
    );
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_storage_path_set(
        self_: Cronet_EngineParamsPtr,
        storage_path: Cronet_String,
    );
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_enable_quic_set(self_: Cronet_EngineParamsPtr, enable_quic: bool);
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_enable_http2_set(self_: Cronet_EngineParamsPtr, enable_http2: bool);
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_enable_brotli_set(
        self_: Cronet_EngineParamsPtr,
        enable_brotli: bool,
    );
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_http_cache_mode_set(
        self_: Cronet_EngineParamsPtr,
        http_cache_mode: Cronet_EngineParams_HTTP_CACHE_MODE,
    );
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_http_cache_max_size_set(
        self_: Cronet_EngineParamsPtr,
        http_cache_max_size: i64,
    );
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_quic_hints_add(
        self_: Cronet_EngineParamsPtr,
        element: Cronet_QuicHintPtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_public_key_pins_add(
        self_: Cronet_EngineParamsPtr,
        element: Cronet_PublicKeyPinsPtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_enable_public_key_pinning_bypass_for_local_trust_anchors_set(
        self_: Cronet_EngineParamsPtr,
        enable_public_key_pinning_bypass_for_local_trust_anchors: bool,
    );
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_network_thread_priority_set(
        self_: Cronet_EngineParamsPtr,
        network_thread_priority: f64,
    );
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_experimental_options_set(
        self_: Cronet_EngineParamsPtr,
        experimental_options: Cronet_String,
    );
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_enable_check_result_get(self_: Cronet_EngineParamsPtr) -> bool;
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_user_agent_get(self_: Cronet_EngineParamsPtr) -> Cronet_String;
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_accept_language_get(self_: Cronet_EngineParamsPtr) -> Cronet_String;
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_storage_path_get(self_: Cronet_EngineParamsPtr) -> Cronet_String;
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_enable_quic_get(self_: Cronet_EngineParamsPtr) -> bool;
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_enable_http2_get(self_: Cronet_EngineParamsPtr) -> bool;
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_enable_brotli_get(self_: Cronet_EngineParamsPtr) -> bool;
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_http_cache_mode_get(
        self_: Cronet_EngineParamsPtr,
    ) -> Cronet_EngineParams_HTTP_CACHE_MODE;
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_http_cache_max_size_get(self_: Cronet_EngineParamsPtr) -> i64;
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_quic_hints_size(self_: Cronet_EngineParamsPtr) -> u32;
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_quic_hints_at(
        self_: Cronet_EngineParamsPtr,
        index: u32,
    ) -> Cronet_QuicHintPtr;
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_quic_hints_clear(self_: Cronet_EngineParamsPtr);
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_public_key_pins_size(self_: Cronet_EngineParamsPtr) -> u32;
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_public_key_pins_at(
        self_: Cronet_EngineParamsPtr,
        index: u32,
    ) -> Cronet_PublicKeyPinsPtr;
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_public_key_pins_clear(self_: Cronet_EngineParamsPtr);
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_enable_public_key_pinning_bypass_for_local_trust_anchors_get(
        self_: Cronet_EngineParamsPtr,
    ) -> bool;
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_network_thread_priority_get(self_: Cronet_EngineParamsPtr) -> f64;
}
unsafe extern "C" {
    pub fn Cronet_EngineParams_experimental_options_get(
        self_: Cronet_EngineParamsPtr,
    ) -> Cronet_String;
}
unsafe extern "C" {
    pub fn Cronet_HttpHeader_Create() -> Cronet_HttpHeaderPtr;
}
unsafe extern "C" {
    pub fn Cronet_HttpHeader_Destroy(self_: Cronet_HttpHeaderPtr);
}
unsafe extern "C" {
    pub fn Cronet_HttpHeader_name_set(self_: Cronet_HttpHeaderPtr, name: Cronet_String);
}
unsafe extern "C" {
    pub fn Cronet_HttpHeader_value_set(self_: Cronet_HttpHeaderPtr, value: Cronet_String);
}
unsafe extern "C" {
    pub fn Cronet_HttpHeader_name_get(self_: Cronet_HttpHeaderPtr) -> Cronet_String;
}
unsafe extern "C" {
    pub fn Cronet_HttpHeader_value_get(self_: Cronet_HttpHeaderPtr) -> Cronet_String;
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_Create() -> Cronet_UrlResponseInfoPtr;
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_Destroy(self_: Cronet_UrlResponseInfoPtr);
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_url_set(self_: Cronet_UrlResponseInfoPtr, url: Cronet_String);
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_url_chain_add(
        self_: Cronet_UrlResponseInfoPtr,
        element: Cronet_String,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_http_status_code_set(
        self_: Cronet_UrlResponseInfoPtr,
        http_status_code: i32,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_http_status_text_set(
        self_: Cronet_UrlResponseInfoPtr,
        http_status_text: Cronet_String,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_all_headers_list_add(
        self_: Cronet_UrlResponseInfoPtr,
        element: Cronet_HttpHeaderPtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_was_cached_set(
        self_: Cronet_UrlResponseInfoPtr,
        was_cached: bool,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_negotiated_protocol_set(
        self_: Cronet_UrlResponseInfoPtr,
        negotiated_protocol: Cronet_String,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_proxy_server_set(
        self_: Cronet_UrlResponseInfoPtr,
        proxy_server: Cronet_String,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_received_byte_count_set(
        self_: Cronet_UrlResponseInfoPtr,
        received_byte_count: i64,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_url_get(self_: Cronet_UrlResponseInfoPtr) -> Cronet_String;
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_url_chain_size(self_: Cronet_UrlResponseInfoPtr) -> u32;
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_url_chain_at(
        self_: Cronet_UrlResponseInfoPtr,
        index: u32,
    ) -> Cronet_String;
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_url_chain_clear(self_: Cronet_UrlResponseInfoPtr);
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_http_status_code_get(self_: Cronet_UrlResponseInfoPtr) -> i32;
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_http_status_text_get(
        self_: Cronet_UrlResponseInfoPtr,
    ) -> Cronet_String;
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_all_headers_list_size(self_: Cronet_UrlResponseInfoPtr) -> u32;
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_all_headers_list_at(
        self_: Cronet_UrlResponseInfoPtr,
        index: u32,
    ) -> Cronet_HttpHeaderPtr;
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_all_headers_list_clear(self_: Cronet_UrlResponseInfoPtr);
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_was_cached_get(self_: Cronet_UrlResponseInfoPtr) -> bool;
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_negotiated_protocol_get(
        self_: Cronet_UrlResponseInfoPtr,
    ) -> Cronet_String;
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_proxy_server_get(
        self_: Cronet_UrlResponseInfoPtr,
    ) -> Cronet_String;
}
unsafe extern "C" {
    pub fn Cronet_UrlResponseInfo_received_byte_count_get(self_: Cronet_UrlResponseInfoPtr) -> i64;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_Create() -> Cronet_UrlRequestParamsPtr;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_Destroy(self_: Cronet_UrlRequestParamsPtr);
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_http_method_set(
        self_: Cronet_UrlRequestParamsPtr,
        http_method: Cronet_String,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_request_headers_add(
        self_: Cronet_UrlRequestParamsPtr,
        element: Cronet_HttpHeaderPtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_disable_cache_set(
        self_: Cronet_UrlRequestParamsPtr,
        disable_cache: bool,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_priority_set(
        self_: Cronet_UrlRequestParamsPtr,
        priority: Cronet_UrlRequestParams_REQUEST_PRIORITY,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_upload_data_provider_set(
        self_: Cronet_UrlRequestParamsPtr,
        upload_data_provider: Cronet_UploadDataProviderPtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_upload_data_provider_executor_set(
        self_: Cronet_UrlRequestParamsPtr,
        upload_data_provider_executor: Cronet_ExecutorPtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_allow_direct_executor_set(
        self_: Cronet_UrlRequestParamsPtr,
        allow_direct_executor: bool,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_annotations_add(
        self_: Cronet_UrlRequestParamsPtr,
        element: Cronet_RawDataPtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_request_finished_listener_set(
        self_: Cronet_UrlRequestParamsPtr,
        request_finished_listener: Cronet_RequestFinishedInfoListenerPtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_request_finished_executor_set(
        self_: Cronet_UrlRequestParamsPtr,
        request_finished_executor: Cronet_ExecutorPtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_idempotency_set(
        self_: Cronet_UrlRequestParamsPtr,
        idempotency: Cronet_UrlRequestParams_IDEMPOTENCY,
    );
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_http_method_get(
        self_: Cronet_UrlRequestParamsPtr,
    ) -> Cronet_String;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_request_headers_size(self_: Cronet_UrlRequestParamsPtr) -> u32;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_request_headers_at(
        self_: Cronet_UrlRequestParamsPtr,
        index: u32,
    ) -> Cronet_HttpHeaderPtr;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_request_headers_clear(self_: Cronet_UrlRequestParamsPtr);
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_disable_cache_get(self_: Cronet_UrlRequestParamsPtr) -> bool;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_priority_get(
        self_: Cronet_UrlRequestParamsPtr,
    ) -> Cronet_UrlRequestParams_REQUEST_PRIORITY;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_upload_data_provider_get(
        self_: Cronet_UrlRequestParamsPtr,
    ) -> Cronet_UploadDataProviderPtr;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_upload_data_provider_executor_get(
        self_: Cronet_UrlRequestParamsPtr,
    ) -> Cronet_ExecutorPtr;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_allow_direct_executor_get(
        self_: Cronet_UrlRequestParamsPtr,
    ) -> bool;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_annotations_size(self_: Cronet_UrlRequestParamsPtr) -> u32;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_annotations_at(
        self_: Cronet_UrlRequestParamsPtr,
        index: u32,
    ) -> Cronet_RawDataPtr;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_annotations_clear(self_: Cronet_UrlRequestParamsPtr);
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_request_finished_listener_get(
        self_: Cronet_UrlRequestParamsPtr,
    ) -> Cronet_RequestFinishedInfoListenerPtr;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_request_finished_executor_get(
        self_: Cronet_UrlRequestParamsPtr,
    ) -> Cronet_ExecutorPtr;
}
unsafe extern "C" {
    pub fn Cronet_UrlRequestParams_idempotency_get(
        self_: Cronet_UrlRequestParamsPtr,
    ) -> Cronet_UrlRequestParams_IDEMPOTENCY;
}
unsafe extern "C" {
    pub fn Cronet_DateTime_Create() -> Cronet_DateTimePtr;
}
unsafe extern "C" {
    pub fn Cronet_DateTime_Destroy(self_: Cronet_DateTimePtr);
}
unsafe extern "C" {
    pub fn Cronet_DateTime_value_set(self_: Cronet_DateTimePtr, value: i64);
}
unsafe extern "C" {
    pub fn Cronet_DateTime_value_get(self_: Cronet_DateTimePtr) -> i64;
}
unsafe extern "C" {
    pub fn Cronet_Metrics_Create() -> Cronet_MetricsPtr;
}
unsafe extern "C" {
    pub fn Cronet_Metrics_Destroy(self_: Cronet_MetricsPtr);
}
unsafe extern "C" {
    pub fn Cronet_Metrics_request_start_set(
        self_: Cronet_MetricsPtr,
        request_start: Cronet_DateTimePtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_Metrics_request_start_move(
        self_: Cronet_MetricsPtr,
        request_start: Cronet_DateTimePtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_Metrics_dns_start_set(self_: Cronet_MetricsPtr, dns_start: Cronet_DateTimePtr);
}
unsafe extern "C" {
    pub fn Cronet_Metrics_dns_start_move(self_: Cronet_MetricsPtr, dns_start: Cronet_DateTimePtr);
}
unsafe extern "C" {
    pub fn Cronet_Metrics_dns_end_set(self_: Cronet_MetricsPtr, dns_end: Cronet_DateTimePtr);
}
unsafe extern "C" {
    pub fn Cronet_Metrics_dns_end_move(self_: Cronet_MetricsPtr, dns_end: Cronet_DateTimePtr);
}
unsafe extern "C" {
    pub fn Cronet_Metrics_connect_start_set(
        self_: Cronet_MetricsPtr,
        connect_start: Cronet_DateTimePtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_Metrics_connect_start_move(
        self_: Cronet_MetricsPtr,
        connect_start: Cronet_DateTimePtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_Metrics_connect_end_set(
        self_: Cronet_MetricsPtr,
        connect_end: Cronet_DateTimePtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_Metrics_connect_end_move(
        self_: Cronet_MetricsPtr,
        connect_end: Cronet_DateTimePtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_Metrics_ssl_start_set(self_: Cronet_MetricsPtr, ssl_start: Cronet_DateTimePtr);
}
unsafe extern "C" {
    pub fn Cronet_Metrics_ssl_start_move(self_: Cronet_MetricsPtr, ssl_start: Cronet_DateTimePtr);
}
unsafe extern "C" {
    pub fn Cronet_Metrics_ssl_end_set(self_: Cronet_MetricsPtr, ssl_end: Cronet_DateTimePtr);
}
unsafe extern "C" {
    pub fn Cronet_Metrics_ssl_end_move(self_: Cronet_MetricsPtr, ssl_end: Cronet_DateTimePtr);
}
unsafe extern "C" {
    pub fn Cronet_Metrics_sending_start_set(
        self_: Cronet_MetricsPtr,
        sending_start: Cronet_DateTimePtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_Metrics_sending_start_move(
        self_: Cronet_MetricsPtr,
        sending_start: Cronet_DateTimePtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_Metrics_sending_end_set(
        self_: Cronet_MetricsPtr,
        sending_end: Cronet_DateTimePtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_Metrics_sending_end_move(
        self_: Cronet_MetricsPtr,
        sending_end: Cronet_DateTimePtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_Metrics_push_start_set(self_: Cronet_MetricsPtr, push_start: Cronet_DateTimePtr);
}
unsafe extern "C" {
    pub fn Cronet_Metrics_push_start_move(self_: Cronet_MetricsPtr, push_start: Cronet_DateTimePtr);
}
unsafe extern "C" {
    pub fn Cronet_Metrics_push_end_set(self_: Cronet_MetricsPtr, push_end: Cronet_DateTimePtr);
}
unsafe extern "C" {
    pub fn Cronet_Metrics_push_end_move(self_: Cronet_MetricsPtr, push_end: Cronet_DateTimePtr);
}
unsafe extern "C" {
    pub fn Cronet_Metrics_response_start_set(
        self_: Cronet_MetricsPtr,
        response_start: Cronet_DateTimePtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_Metrics_response_start_move(
        self_: Cronet_MetricsPtr,
        response_start: Cronet_DateTimePtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_Metrics_request_end_set(
        self_: Cronet_MetricsPtr,
        request_end: Cronet_DateTimePtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_Metrics_request_end_move(
        self_: Cronet_MetricsPtr,
        request_end: Cronet_DateTimePtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_Metrics_socket_reused_set(self_: Cronet_MetricsPtr, socket_reused: bool);
}
unsafe extern "C" {
    pub fn Cronet_Metrics_sent_byte_count_set(self_: Cronet_MetricsPtr, sent_byte_count: i64);
}
unsafe extern "C" {
    pub fn Cronet_Metrics_received_byte_count_set(
        self_: Cronet_MetricsPtr,
        received_byte_count: i64,
    );
}
unsafe extern "C" {
    pub fn Cronet_Metrics_request_start_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
}
unsafe extern "C" {
    pub fn Cronet_Metrics_dns_start_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
}
unsafe extern "C" {
    pub fn Cronet_Metrics_dns_end_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
}
unsafe extern "C" {
    pub fn Cronet_Metrics_connect_start_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
}
unsafe extern "C" {
    pub fn Cronet_Metrics_connect_end_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
}
unsafe extern "C" {
    pub fn Cronet_Metrics_ssl_start_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
}
unsafe extern "C" {
    pub fn Cronet_Metrics_ssl_end_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
}
unsafe extern "C" {
    pub fn Cronet_Metrics_sending_start_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
}
unsafe extern "C" {
    pub fn Cronet_Metrics_sending_end_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
}
unsafe extern "C" {
    pub fn Cronet_Metrics_push_start_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
}
unsafe extern "C" {
    pub fn Cronet_Metrics_push_end_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
}
unsafe extern "C" {
    pub fn Cronet_Metrics_response_start_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
}
unsafe extern "C" {
    pub fn Cronet_Metrics_request_end_get(self_: Cronet_MetricsPtr) -> Cronet_DateTimePtr;
}
unsafe extern "C" {
    pub fn Cronet_Metrics_socket_reused_get(self_: Cronet_MetricsPtr) -> bool;
}
unsafe extern "C" {
    pub fn Cronet_Metrics_sent_byte_count_get(self_: Cronet_MetricsPtr) -> i64;
}
unsafe extern "C" {
    pub fn Cronet_Metrics_received_byte_count_get(self_: Cronet_MetricsPtr) -> i64;
}
unsafe extern "C" {
    pub fn Cronet_RequestFinishedInfo_Create() -> Cronet_RequestFinishedInfoPtr;
}
unsafe extern "C" {
    pub fn Cronet_RequestFinishedInfo_Destroy(self_: Cronet_RequestFinishedInfoPtr);
}
unsafe extern "C" {
    pub fn Cronet_RequestFinishedInfo_metrics_set(
        self_: Cronet_RequestFinishedInfoPtr,
        metrics: Cronet_MetricsPtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_RequestFinishedInfo_metrics_move(
        self_: Cronet_RequestFinishedInfoPtr,
        metrics: Cronet_MetricsPtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_RequestFinishedInfo_annotations_add(
        self_: Cronet_RequestFinishedInfoPtr,
        element: Cronet_RawDataPtr,
    );
}
unsafe extern "C" {
    pub fn Cronet_RequestFinishedInfo_finished_reason_set(
        self_: Cronet_RequestFinishedInfoPtr,
        finished_reason: Cronet_RequestFinishedInfo_FINISHED_REASON,
    );
}
unsafe extern "C" {
    pub fn Cronet_RequestFinishedInfo_metrics_get(
        self_: Cronet_RequestFinishedInfoPtr,
    ) -> Cronet_MetricsPtr;
}
unsafe extern "C" {
    pub fn Cronet_RequestFinishedInfo_annotations_size(self_: Cronet_RequestFinishedInfoPtr)
    -> u32;
}
unsafe extern "C" {
    pub fn Cronet_RequestFinishedInfo_annotations_at(
        self_: Cronet_RequestFinishedInfoPtr,
        index: u32,
    ) -> Cronet_RawDataPtr;
}
unsafe extern "C" {
    pub fn Cronet_RequestFinishedInfo_annotations_clear(self_: Cronet_RequestFinishedInfoPtr);
}
unsafe extern "C" {
    pub fn Cronet_RequestFinishedInfo_finished_reason_get(
        self_: Cronet_RequestFinishedInfoPtr,
    ) -> Cronet_RequestFinishedInfo_FINISHED_REASON;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct stream_engine {
    pub obj: *mut ::core::ffi::c_void,
    pub annotation: *mut ::core::ffi::c_void,
}
impl Default for stream_engine {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct bidirectional_stream {
    pub obj: *mut ::core::ffi::c_void,
    pub annotation: *mut ::core::ffi::c_void,
}
impl Default for bidirectional_stream {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct bidirectional_stream_header {
    pub key: *const ::core::ffi::c_char,
    pub value: *const ::core::ffi::c_char,
}
impl Default for bidirectional_stream_header {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct bidirectional_stream_header_array {
    pub count: usize,
    pub capacity: usize,
    pub headers: *mut bidirectional_stream_header,
}
impl Default for bidirectional_stream_header_array {
    fn default() -> Self {
        let mut s = ::core::mem::MaybeUninit::<Self>::uninit();
        unsafe {
            ::core::ptr::write_bytes(s.as_mut_ptr(), 0, 1);
            s.assume_init()
        }
    }
}
#[repr(C)]
#[derive(Debug, Default, Copy, Clone)]
pub struct bidirectional_stream_callback {
    pub on_stream_ready:
        ::core::option::Option<unsafe extern "C" fn(stream: *mut bidirectional_stream)>,
    pub on_response_headers_received: ::core::option::Option<
        unsafe extern "C" fn(
            stream: *mut bidirectional_stream,
            headers: *const bidirectional_stream_header_array,
            negotiated_protocol: *const ::core::ffi::c_char,
        ),
    >,
    pub on_read_completed: ::core::option::Option<
        unsafe extern "C" fn(
            stream: *mut bidirectional_stream,
            data: *mut ::core::ffi::c_char,
            bytes_read: ::core::ffi::c_int,
        ),
    >,
    #[doc = " Invoked when all data passed to bidirectional_stream_write() is\n sent. To continue writing, call bidirectional_stream_write()."]
    pub on_write_completed: ::core::option::Option<
        unsafe extern "C" fn(stream: *mut bidirectional_stream, data: *const ::core::ffi::c_char),
    >,
    pub on_response_trailers_received: ::core::option::Option<
        unsafe extern "C" fn(
            stream: *mut bidirectional_stream,
            trailers: *const bidirectional_stream_header_array,
        ),
    >,
    #[doc = " Invoked when there is no data to be read or written and the stream is\n closed successfully remotely and locally. Once invoked, no further callback\n methods will be invoked."]
    pub on_succeded:
        ::core::option::Option<unsafe extern "C" fn(stream: *mut bidirectional_stream)>,
    #[doc = " Invoked if the stream failed for any reason after\n bidirectional_stream_start(). HTTP/2 error codes are\n mapped to chrome net error codes. Once invoked, no further callback methods\n will be invoked."]
    pub on_failed: ::core::option::Option<
        unsafe extern "C" fn(stream: *mut bidirectional_stream, net_error: ::core::ffi::c_int),
    >,
    #[doc = " Invoked if the stream was canceled via\n bidirectional_stream_cancel(). Once invoked, no further callback\n methods will be invoked."]
    pub on_canceled:
        ::core::option::Option<unsafe extern "C" fn(stream: *mut bidirectional_stream)>,
}
unsafe extern "C" {
    pub fn bidirectional_stream_create(
        engine: *mut stream_engine,
        annotation: *mut ::core::ffi::c_void,
        callback: *const bidirectional_stream_callback,
    ) -> *mut bidirectional_stream;
}
unsafe extern "C" {
    pub fn bidirectional_stream_destroy(stream: *mut bidirectional_stream) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Disables or enables auto flush. By default, data is flushed after\n every bidirectional_stream_write(). If the auto flush is disabled,\n the client should explicitly call bidirectional_stream_flush to flush\n the data."]
    pub fn bidirectional_stream_disable_auto_flush(
        stream: *mut bidirectional_stream,
        disable_auto_flush: bool,
    );
}
unsafe extern "C" {
    #[doc = " Delays sending request headers until bidirectional_stream_flush()\n is called. This flag is currently only respected when QUIC is negotiated.\n When true, QUIC will send request header frame along with data frame(s)\n as a single packet when possible."]
    pub fn bidirectional_stream_delay_request_headers_until_flush(
        stream: *mut bidirectional_stream,
        delay_headers_until_flush: bool,
    );
}
unsafe extern "C" {
    pub fn bidirectional_stream_start(
        stream: *mut bidirectional_stream,
        url: *const ::core::ffi::c_char,
        priority: ::core::ffi::c_int,
        method: *const ::core::ffi::c_char,
        headers: *const bidirectional_stream_header_array,
        end_of_stream: bool,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn bidirectional_stream_read(
        stream: *mut bidirectional_stream,
        buffer: *mut ::core::ffi::c_char,
        capacity: ::core::ffi::c_int,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    pub fn bidirectional_stream_write(
        stream: *mut bidirectional_stream,
        buffer: *const ::core::ffi::c_char,
        buffer_length: ::core::ffi::c_int,
        end_of_stream: bool,
    ) -> ::core::ffi::c_int;
}
unsafe extern "C" {
    #[doc = " Flushes pending writes. This method should not be called before invocation of\n on_stream_ready() method of the bidirectional_stream_callback.\n For each previously called bidirectional_stream_write()\n a corresponding on_write_completed() callback will be invoked when the buffer\n is sent."]
    pub fn bidirectional_stream_flush(stream: *mut bidirectional_stream);
}
unsafe extern "C" {
    pub fn bidirectional_stream_cancel(stream: *mut bidirectional_stream);
}
unsafe extern "C" {
    pub fn bidirectional_stream_is_done(stream: *mut bidirectional_stream) -> bool;
}
pub type Cronet_DialerFunc = ::core::option::Option<
    unsafe extern "C" fn(
        context: *mut ::core::ffi::c_void,
        address: *const ::core::ffi::c_char,
        port: u16,
    ) -> ::core::ffi::c_int,
>;
pub type Cronet_UdpDialerFunc = ::core::option::Option<
    unsafe extern "C" fn(
        context: *mut ::core::ffi::c_void,
        address: *const ::core::ffi::c_char,
        port: u16,
        out_local_address: *mut ::core::ffi::c_char,
        out_local_port: *mut u16,
    ) -> ::core::ffi::c_int,
>;
unsafe extern "C" {
    pub fn Cronet_Engine_GetStreamEngine(arg1: Cronet_EnginePtr) -> *mut stream_engine;
}
unsafe extern "C" {
    pub fn Cronet_Engine_SetDialer(
        arg1: Cronet_EnginePtr,
        arg2: Cronet_DialerFunc,
        arg3: *mut ::core::ffi::c_void,
    );
}
unsafe extern "C" {
    pub fn Cronet_Engine_SetUdpDialer(
        arg1: Cronet_EnginePtr,
        arg2: Cronet_UdpDialerFunc,
        arg3: *mut ::core::ffi::c_void,
    );
}
unsafe extern "C" {
    pub fn Cronet_Engine_CloseAllConnections(arg1: Cronet_EnginePtr);
}
unsafe extern "C" {
    pub fn Cronet_CreateCertVerifierWithRootCerts(arg1: Cronet_String) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn Cronet_Engine_SetMockCertVerifierForTesting(
        arg1: Cronet_EnginePtr,
        arg2: *mut ::core::ffi::c_void,
    );
}
